language: python
python:
  - "2.7"
  - "3.5"
  - "nightly"
install:
  - "pip install --upgrade pip"
  - "pip install wheel"
  - "pip wheel . --process-dependency-links"
  - "pip install . --process-dependency-links"
script: git-credential-keepasshttp
